server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: consumer # 路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://consumer #匹配后提供服务的路由地址
          predicates:
            - Path=/api/** # 断言，路径相匹配的进行路由
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
logging:
  level:
    com: debug
    org: debug